name: train_op
description: Train XGBoost model and save as joblib.
inputs:
  - {name: x_train_path, type: Dataset}
  - {name: y_train_path, type: Dataset}
outputs:
  - {name: model_dir, type: Model}
implementation:
  container:
    image: IMAGE_URI_TRAIN
    command: [
          "python", "-u", "src/main.py",
          "--x_train_path", {inputPath: x_train_path},
          "--y_train_path", {inputPath: y_train_path},
          "--model_dir", {outputPath: model_dir}
        ]
